---
- hosts: localhost
  gather_facts: False
  tasks:
  - name: "provision nodes"
    duffy_ansible:
      state: "present"
      count: 1
    register: daa
  - debug:
      var: daa
  - command: 'echo "ssid: {{ daa.ssid }} -- {{ daa.hosts }}"'
  - name: "teardown nodes from ssid"
    duffy_ansible:
      state: "absent"
      ssid: "{{ daa.ssid }}"
